env:
  browser: true
  es6: true
  jest: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 11
  ecmaFeatures:
    jsx: true
  sourceType: module
extends:
  - standard
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - airbnb
  - prettier
  - plugin:prettier/recommended
  - plugin:jsx-a11y/recommended
plugins:
  - react
  - jsx-a11y
  - jest
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
rules:
  #  general
  prettier/prettier:
    - error
    - usePrettierrc: true
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
      optionalDependencies: false
      peerDependencies: false
  jsx-a11y/anchor-is-valid: off
  jsx-a11y/label-has-associated-control:
    - error
    - assert: either
  #   react
  react/state-in-constructor: off
  react/button-has-type: off
  react/prop-types: 0
  react/react-in-jsx-scope: off
  react/jsx-props-no-spreading: off
  no-console: off
  camelcase: off
  no-else-return: off
  import/prefer-default-export: off
  comma-dangle: off
